### ISSUE TITLE
Add codeowners file.

### ISSUE THREAD

**Issue by sumanabhi** [NoteXCommunity/note-x#32]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
This is to add codeowners for different branches and also assign default reviewers based on the branching rules.

**Describe alternatives you've considered**
Na
**Additional context**
NA

**Comment by hadiyarajesh** [comment]
Hi @sumanabhi  can you close this issue if there's nothing pending to work on it?
